### PR TITLE
PLF-7076 [Privacy] Uploading a document in my documents fires an activity visible to my network

### PR DESCRIPTION
**Pull request by nttuyen**

### CODE REVIEW

**Comment by nttuyen** [comment]
This logic code is on integration project. I tried to configure social and ecms services on this to add unit test but they are too much and still not successful.
Could we ignore unit test for this?

**Comment by thomasdelhomenie** [comment]
You are trying to do integration tests. I was talking about unit tests (external services must be mocked or "stubbed" in this case). Can you give it a try please ?

**Comment by nttuyen** [comment]
ahh... ok, let me try with mock the things

**Comment by nttuyen** [comment]
Look good to me

**Pull request closed without merging**
