### PR TITLE
WIKI-1448 : change WIKI_PAGE_NAME to WikiPortlet

### PR DESCRIPTION
**Pull request by AzmiTouil**
The wiki space application has a URI =wiki. The problem that when I delete the wiki application and add it again, the new one has a different URI = "WikiPortlet", because it's considered as a new portlet and takes its name as URI.
To fix it,  I have changed the default wiki portlet URI to "WikiPortlet".

### CODE REVIEW

**Comment by plamarque** [comment]
WirkiPortlet in the URL is ugly. Can we change the other way ? Doing so that whrn we remove then readd wiki app in space, it comes back under /wiki instead of /WikiPortlet ?

**Comment by AzmiTouil** [comment]
IMO this solution is the simplest and least risky.
because when adding a new app in space, the portlet name is considered as URI of this app. So if you want to change the other way we need to change the portlet name that used in many modules as "WikiPortlet",   WDYT ?

**Comment by plamarque** [comment]
> IMO this solution is the simplest and least risky.
> because when adding a new app in space, the portlet name is considered as URI of this app. So if you want to change the other way we need to change the portlet name that used in many modules as "WikiPortlet", WDYT ?

I cas more about user experience. Thus when I specified them (yep, I authored that spec many years ago), I cared to have simple and easy to remember uris. The spec didn't consider the scenario of removing then re-adding, so the developers decided they would use the portlet name, which lead to an ugly URI. We have the opportunity to fix it now. please fix it properly instead of generating ugly space urls.

**Comment by AzmiTouil** [comment]
Okay

**Pull request closed without merging**
