### PR TITLE
WIKI-1252: catch missing resource exception for editing wiki page com…

### PR DESCRIPTION
**Pull request by wkhessairi**
…ment

### CODE REVIEW

**Comment by wkhessairi** [comment]
When a comment is added through editing, the main problem, is that there is no key of resource bundle for the comment it self (in https://github.com/exodev/integration/blob/develop/integ-wiki/integ-wiki-social/src/main/java/org/exoplatform/wiki/ext/impl/WikiSpaceActivityPublisher.java#L181 , the argument for the key is null). What I have done in such case, I returned the key itself, which corresponds to the comment added.
Otherwise, we should define a key for such argument, which is , IMO, should be specified, because we will modify the structure of the comment added through editing.

**Comment by thomasdelhomenie** [comment]
But why do we even try to get the resource bundle value of the comment itself ? That does not make sense to me.

**Comment by wkhessairi** [comment]
because, through editing, a comment is added to the social activity saying that "the title of the page xxx is edited to xxxx ..."
and then we should append to the comment, the comment added ("note de version")

**Comment by wkhessairi** [comment]
and we try to get the key of the comment to append it. I propose "<br>version note:</br>{0}" for English
and "<br>note de version:</br>{0}" for French

**Comment by wkhessairi** [comment]
Unit tests cannot be added because the method is private, and the service is a plugin launched from Wiki project when a wiki page is edited

**Pull request closed without merging**
