### PR TITLE
Fix/4.4.x/cal 1255

### PR DESCRIPTION
**Pull request by kmenzli**

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
A method which convert an url into a link is already available on client side : eXo.calendar.EventTooltip.urlify. It has been implemented to fix https://jira.exoplatform.org/browse/CAL-1226 (commit https://github.com/exodev/calendar/commit/1a05125c61175da3cd936224608a044c307d2bb3) and it should be re-used here IMO.

**Comment by kmenzli** [comment]
I'm not aware about this js method, however, why I should load this js in activity stream? thus I prefer a server side solution in this case.
Aside from client/server side solution, the js method pushed to solve CAL-1226 doesn't cover all cases (for example try to put in the description http+https+ww links ==> links will be broken )

**Comment by thomasdelhomenie** [comment]
> I'm not aware about this js method, however, why I should load this js in activity stream?

What do you mean ? Because it a calendar js ? If so, I agree it should be moved to the commons project as I proposed in CAL-1226, but it has not been done. Then you can use it anywhere.

> thus I prefer a server side solution in this case.

Why ? It would duplicate code.

> Aside from client/server side solution, the js method pushed to solve CAL-1226 doesn't cover all cases (for example try to put in the description http+https+ww links ==> links will be broken )

Feel free to fix it if necessary :)

**Comment by kmenzli** [comment]
PR update, despite concerns I have to use a client-side solution in this particular context

**Comment by thomasdelhomenie** [comment]
You still did not tell why a server side solution would be better than a client side solution, that's would help to understand your concerns :)
My initial remark was a concern about code duplication, not about server/client side. We already have a function to do it (and it was initially done in js, in Task project), it would be a pity to duplicate it.

**Comment by kmenzli** [comment]
The context of this jira is different than CAL-1226. Here, we have to perform a String transformation for each activity. In CAL-1226 the script is invoked only on time by page (when a user select an event). I would prefer to store a classic link in the event description rather than a plain text, then in the Stream, I have only to display what I have in the DB without any processing  ==> Like when you share a link in the Stream ==> it's stored as a HTML link (using the tag <a>).

**Pull request closed without merging**
