### PR TITLE
ECMS-7450: Document Viewer for txt files

### PR DESCRIPTION
**Pull request by wkhessairi**

### CODE REVIEW

**Comment by thomasdelhomenie** [comment]
My understanding is that OfficeDocumentThumbnailPlugin is for Office documents (doc, xls, ...) IMO, not for txt documents. And there is no thumbnail for txt files, only an icon.

**Comment by wkhessairi** [comment]
I think, such case should be specified, either we will display a thumbnail for text files or not

**Comment by thomasdelhomenie** [comment]
The issue is only related to the preview of the txt document, not about the thumbnail, so I think we should keep it simple and do not manage a thumbnail (we just keep the txt icon).
@wkhessairi @boubaker WDYT ?

**Comment by boubaker** [comment]
> The issue is only related to the preview of the txt document, not about the thumbnail, so I think we should keep it simple and do not manage a thumbnail (we just keep the txt icon).

To make the preview more adequate, we can manage it as any other office document type. This is more simple IMO and make it more coherent.

**Comment by wkhessairi** [comment]
For me, I think that displaying the thumbnail or not are both possible. But this is a functional behaviour that should be specified in the product specifications

**Comment by boubaker** [comment]
The project has been deleted, thus, this PR is to be moved to ecms addon if needed

**Pull request closed without merging**
