### PR TITLE
SOC-5901 Replies posted twice

### PR DESCRIPTION
**Pull request by boubaker**

### CODE REVIEW

**Comment by boubaker** [comment]
> Can't we just remove the creation of the comment in ForumUIActivity.createPost since it is already handled by the listener ?

In fact, the creation of activity comment and topic post has to be made synchronously to update the Activity view, while the creation of the comment in `ForumUIActivity.createPost` is asynchronous.

> It would avoid to do this workaround using a ThreadLocal.

This strategy is already used in Integ-ECMS ( `org.exoplatform.services.cms.jcrext.activity.ActivityCommonService.setCreating()` ), I don't really agree with it (Poor Model & Design), but unfortunately, I didn't found a quick solution that will avoid additional eventual regression (no complex modifications)

> Or maybe fetching the activity comments in the publisher to check if the comment is already created (since the comments data have the post id) ?

This could be a good idea, but it will add additional processing on activity post to request the database, while this information already exists in memory. (Performance regression)

**Comment by thomasdelhomenie** [comment]
> In fact, the creation of activity comment and topic post has to be made synchronously to update the Activity view, while the creation of the comment in ForumUIActivity.createPost is asynchronous.

Can we find a way to allow to do it synchronously in this case (by updating the API) ?

> This strategy is already used in Integ-ECMS ( org.exoplatform.services.cms.jcrext.activity.ActivityCommonService.setCreating() ), I don't really agree with it (Poor Model & Design), but unfortunately, I didn't found a quick solution that will avoid additional eventual regression (no complex modifications)

That's what I would like to avoid, a quick but poor solution. We agree on the point that this solution is not really good. Do you have a non-quick solution in mind ?

> This could be a good idea, but it will add additional processing on activity post to request the database, while this information already exists in memory. (Performance regression)

Yes, it can have an impact, it should be measured.

**Comment by boubaker** [comment]
> Can we find a way to allow to do it synchronously in this case (by updating the API) ?
Could have an impact on performances too, which I would like to avoid.

**Comment by boubaker** [comment]
Done

**Comment by thomasdelhomenie** [comment]
Looks really better :+1: 
Just a thought, can't we fall in a race condition in case where the async task will be executed before the call to saveComment in ForumUIActivity.PostCommentActionListener#execute ? The async task will create the comment since it will not find it.

**Comment by boubaker** [comment]
> race

rare ?

> Just a thought, can't we fall in a race condition in case where the async task will be executed before the call to saveComment in ForumUIActivity.PostCommentActionListener#execute ? The async task will create the comment since it will not find it.

That's why I didn't used this solution at the first place. We 'll discuss more about this by voice.

**Comment by thomasdelhomenie** [comment]
> rare ?

No, race condition : https://en.wikipedia.org/wiki/Race_condition (which can be rare indeed :wink: )

I think an easy way to solve this issue is to create the activity comment before creating the forum post.

**Comment by boubaker** [comment]
> I think an easy way to solve this issue is to create the activity comment before creating the forum post.

Not really easy without an eventual regression, see variable isMigratedActivity in org.exoplatform.forum.ext.impl.ForumUIActivity.PostCommentActionListener.execute(Event<BaseUIActivity>)
And, of course, even by creating the comment before the post, you will not have an efficient way to test on existence of comment in ForumSpaceActivityPublisher.
As I said at the first place, the API itself was built with poor design, thus no efficient way to make this elegant only if we spend more time on implementing it and testing it to not have a regression.
As you know, regressions are dangerous in this period. IMO, we can manage the improvement of this API when migrating to RDBMS, or we should revert INTEG-477.

A call would be simpler, isn't it ? (Else it will take a lot of time by discussing it here ;-))

**Comment by boubaker** [comment]
First commit, reverted.

as Agreed, both commits has to be combined to manage this correctly, and we'll have to provide a better way to do when refactoring this API.

**Comment by thomasdelhomenie** [comment]
:+1:

**Pull request merged**
